import type { Metadata } from "next";
import { fonts } from "./fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${fonts.bookkBold.variable} ${fonts.bookkLight.variable} ${fonts.notoSansKRVar.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
