import type { Metadata } from "next";
import { fonts } from "./fonts";
import "./globals.css";

import { Navbar } from "./components/layout/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${fonts.hsBombaram.variable} ${fonts.pretendardVariable.variable}`}>
      <body className="font-main">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
